[profile.release]
# 发布模式开启优化程序大小
opt-level = "s"


[workspace]
members = [
    "build_helper",
    "macros",
    "main",
    "peeper",
    "proxy32",
    "jab-sys",
    "resources",
    "win-wrap"
]
resolver = "2"
