[profile.release]
# 发布模式开启优化程序大小
opt-level = "s"


[workspace]
members = [
    'access-lib',
    "build_helper",
    "macros",
    "main",
    "peeper",
    "proxy32",
    "resources",
    "utils",
    "win-wrap"
]
resolver = "2"
