[package]
name = "main"
description = "RigelA screen reader (rsr)."
version = "0.1.0"
edition = "2021"
authors = [
    "mzdk100 <mzdk100@foxmail.com>",
    "lwboy <liwenboy2008@126.com>"
]
keywords = ["读屏软件", "无障碍"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://gitcode.net/mzdk100/rigela.git"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.i18n]
# 配置I18N国际化多语言支持
default-locale = "zh-CN"
# 这个配置让'cargo i18n'命令行工具知道在哪里可以找到你的翻译。要保证和传给“rust_i18n::i18n！”方法的路径相同。
load-path = "locale"

[dependencies.peeper]
# 跨进程收集信息（例如输入法和GDI绘图接口信息）
path = "../peeper"

[dependencies.win-wrap]
# Windows Api的安全封装
path = "../win-wrap"

[dependencies.tokio]
# 异步运行时（携程框架）
version = "1.35.1"
features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "process",
    "time"
]

[build-dependencies.embed-resource]
# 嵌入资源信息到程序中
version = "2.4.0"

[build-dependencies.cargo-rigela]
path = "../build_helper"

[dependencies.rigela-proxy32]
path = "../proxy32"

[dependencies.rigela-macros]
path = "../macros"

[dependencies.rigela-resources]
path = "../resources"

[dependencies.rigela-utils]
path = "../utils"

[dependencies.serde]
# 用于数据序列化和反序列化
version = "1.0.145"
features = ["derive"]

[dependencies.toml]
version = "0.8.8"

[dependencies]
# 查看日期和时间
chrono = "0.4.31"
# 配置I18N国际化多语言支持
rust-i18n = "3.0.0"
# gui库，winit的版本跟eframe库使用的winit版本走，不要使用最新，否则无法编译
winit = "0.29.9"
eframe = "0.25.0"
log = "0.4.20"
