[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.peeper]
# 跨进程收集信息（例如输入法和GDI绘图接口信息）
path = "../peeper"

[dependencies.win-wrap]
# Windows Api的安全封装
path = "../win-wrap"

[dependencies.tokio]
# 异步运行时（携程框架）
version = "1.35.0"
features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "time"
]

[build-dependencies.embed-resource]
# 嵌入资源信息到程序中
version = "2.4.0"
