[package]
name = "a11y"  # A11y is the abbreviation for accessibility
keywords.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.win-wrap]
path = "../win-wrap"
features = ["msaa", "com"]

[dependencies.rigela-utils]
path = "../utils"
features = ["library"]

[dependencies.windows]
version = "0.54.0"
features = [
    "implement",
    "windows-interface",
    "Win32_System_Com",
    "Win32_System_Variant",
    "Win32_UI_Accessibility"
]
