[package]
name = "a11y"  # A11y is the abbreviation for accessibility
keywords.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-interface = "0.52.0"

[dependencies.win-wrap]
path = "../win-wrap"

[dependencies.rigela-utils]
path = "../utils"

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_System_Com",
    "Win32_System_Variant",
    "Win32_UI_Accessibility"
]
