[package]
name = "rigela-resources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitar = "0.11.0"
blake2 = "0.10.6"
url = "2.5.0"

[dependencies.futures-util]
version = "0.3.30"
default-features = false
features = ["std"]

[dependencies.tokio]
version = "1.35.1"
features = ["fs", "io-std", "macros", "time", "rt-multi-thread"]

[build-dependencies]
blake2 = "0.10.6"

[build-dependencies.bitar]
version = "0.11.0"
features = ["compress"]

[build-dependencies.tokio]
version = "1.35.1"
features = ["fs", "io-std", "macros", "time", "rt-multi-thread"]

[build-dependencies.futures-util]
version = "0.3.30"
default-features = false
features = ["std"]
