[build]
target = [
    "x86_64-pc-windows-msvc",
    "i686-pc-windows-msvc"
]

[alias]
# 用于建立完整的构建环境
mkenv = ["install", "cargo-rigela", "--path", "build_helper", "--target", "x86_64-pc-windows-msvc"]
ck = ["rigela", "check"]
# 开发模式
dev = ["rigela", "run"]
dev32 = ["run", "--target", "i686-pc-windows-msvc"]
# 发布模式
rel = ["rigela", "build", "--release"]

[env]

[env.PROTOC]
value = "tools/protoc.exe"
relative = true

[env.RUST_BACKTRACE]
value = "1"