[package]
name = "rigela-utils"
keywords.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 操作剪贴板
clipboard = "0.5.0"
# 获取用户目录的路径
home = "0.5.9"
# 输出日志
log = "0.4.20"
# 记录日志
log4rs = "1.3.0"

[dependencies.serde]
# 用于数据序列化和反序列化
version = "1.0.196"
features = ["derive"]

[dependencies.tokio]
# 异步运行时（携程框架）
version = "1.36.0"
features = [
    "macros",
    "time"
]

[dependencies.serde_json_bytes]
version = "0.2.2"

[dependencies.rigela-resources]
path = "../resources"

[dependencies.win-wrap]
path = "../win-wrap"
