[package]
name = "peeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retour = "0.3.1"
once_cell = "1.19.0"

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices"
]

[lib]
name = "peeper"
crate-type = ["rlib", "dylib"]