[package]
name = "peeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retour = "0.3.1"
once_cell = "1.19.0"
log = "0.4.20"

[dependencies.win-wrap]
path = "../win-wrap"

[dependencies.rigela-utils]
path = "../utils"

[dependencies.windows]
version = "0.52.0"
features = ["Win32_Foundation"]

[dependencies.tokio]
features = ["fs", "io-util", "net"]
version = "1.35.1"

[lib]
name = "peeper"
crate-type = ["rlib", "dylib"]