[package]
name = "peeper"
keywords.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retour = "0.3.1"
once_cell = "1.19.0"
log = "0.4.20"

[dependencies.win-wrap]
path = "../win-wrap"

[dependencies.rigela-utils]
path = "../utils"

[dependencies.windows]
version = "0.52.0"
features = ["Win32_Foundation"]

[dependencies.serde]
features = ["derive"]
version = "1.0.196"

[dependencies.tokio]
features = [
    "rt-multi-thread",
    "fs",
    "io-util",
    "net",
    "sync"
]
version = "1.36.0"

[lib]
name = "peeper"
crate-type = ["rlib", "dylib"]
