name: Rust

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make env
      run: cargo mkenv
    - name: Build
      run: cargo rigela build --verbose
    - name: Run tests
      run: cargo test --verbose
